services:
  accounts:
    image: "asthattyagi/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - accounts-network       
  loans:
    image: "asthattyagi/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: "700m"   
    networks:
      - accounts-network      
  cards:
    image: "asthattyagi/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: "700m"  
    networks:
      - accounts-network
networks:
  accounts-network:            
                    
       